"""add_field_courseType_to_recipe_model

Revision ID: 13624cb5abaa
Revises: 41788dc7373a
Create Date: 2026-05-08 09:48:28.634605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13624cb5abaa'
down_revision: Union[str, None] = '41788dc7373a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('course_type', sa.Enum('STARTER', 'MAIN_COURSE', 'DESSERT', name='coursetype', native_enum=False, length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'course_type')
    # ### end Alembic commands ###
