"""change created_by_user_id to string uuid

Revision ID: 1e8073911d1a
Revises: 13624cb5abaa
Create Date: 2026-05-09 16:04:09.242361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8073911d1a'
down_revision: Union[str, None] = '13624cb5abaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True,
               postgresql_using='created_by_user_id::text')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'created_by_user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='created_by_user_id::int')
    # ### end Alembic commands ###
