"""Initial recipe models

Revision ID: 41788dc7373a
Revises: 
Create Date: 2026-05-07 13:36:44.470095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41788dc7373a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='List of tags issus from Enums'),
    sa.Column('free_tags', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('proteins_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('fats_per_100g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=350), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel', native_enum=False, length=50), nullable=False),
    sa.Column('tags', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('cuisine_origin', sa.Enum('EUROPE', 'FRENCH', 'ITALIAN', 'SPANISH', 'GREEK', 'GERMAN', 'ASIA', 'CHINESE', 'JAPANESE', 'THAI', 'INDIAN', 'KOREAN', 'VIETNAMESE', 'AFRICA', 'MOROCCAN', 'ETHIOPIAN', 'SENEGALESE', 'SOUTH_AMERICA', 'MEXICAN', 'AMERICAN', 'BRAZILIAN', 'PERUVIAN', 'MIDDLE_EAST', 'LEBANESE', 'TURKISH', 'IRANIAN', 'OCEANIA', 'AUSTRALIAN', 'POLYNESIAN', name='cuisineorigin', native_enum=False, length=50), nullable=False),
    sa.Column('origin_recipe', sa.Enum('WEB', 'BOOK', 'TV', 'PERSONAL', name='recipeorigin', native_enum=False, length=50), nullable=False),
    sa.Column('book_name', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
