"""add handler for changing pwd

Revision ID: 14a0d588dad7
Revises: 641cc27f15c4
Create Date: 2026-05-24 16:13:37.013522
"""

revision = "14a0d588dad7"
down_revision = "641cc27f15c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
