"""add MFA TOTP & OAUTH2

Revision ID: 641cc27f15c4
Revises: 642a52025ebf
Create Date: 2026-05-23 11:47:02.569842
"""

from alembic import op
import sqlalchemy as sa


revision = "641cc27f15c4"
down_revision = "642a52025ebf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("totp_secret", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "two_factor_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "users", sa.Column("two_factor_method", sa.String(length=10), nullable=True)
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "two_factor_method")
    op.drop_column("users", "two_factor_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
