"""Initial recipe models

Revision ID: 36787d520729
Revises: 
Create Date: 2026-05-19 12:19:10.043213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36787d520729'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('raw_ingredient', sa.Text(), nullable=False),
    sa.Column('suggested_match', sa.String(length=300), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'MANUAL', name='macroerrorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('resolved_name', sa.String(length=300), nullable=True),
    sa.Column('calories_manual', sa.Float(), nullable=True),
    sa.Column('proteines_manual', sa.Float(), nullable=True),
    sa.Column('glucides_manual', sa.Float(), nullable=True),
    sa.Column('lipides_manual', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_errors_slug'), 'macro_errors', ['slug'], unique=True)
    op.create_index(op.f('ix_macro_errors_user_id'), 'macro_errors', ['user_id'], unique=False)
    op.create_table('nutrition_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('nom_fr', sa.String(length=300), nullable=False),
    sa.Column('nom_en', sa.String(length=300), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteines', sa.Float(), nullable=False),
    sa.Column('glucides', sa.Float(), nullable=False),
    sa.Column('lipides', sa.Float(), nullable=False),
    sa.Column('fibres', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('CIQUAL', 'NUTRITIONIX', 'USER', name='nutritionsource', native_enum=False, length=20), nullable=False),
    sa.Column('ciqual_id', sa.String(length=50), nullable=True),
    sa.Column('nutritionix_id', sa.String(length=100), nullable=True),
    sa.Column('nutritionix_enriched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciqual_id')
    )
    op.create_index(op.f('ix_nutrition_items_slug'), 'nutrition_items', ['slug'], unique=True)
    op.create_table('unit_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('aliment_type', sa.String(length=100), nullable=True),
    sa.Column('grammes', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_conversions_slug'), 'unit_conversions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_conversions_slug'), table_name='unit_conversions')
    op.drop_table('unit_conversions')
    op.drop_index(op.f('ix_nutrition_items_slug'), table_name='nutrition_items')
    op.drop_table('nutrition_items')
    op.drop_index(op.f('ix_macro_errors_user_id'), table_name='macro_errors')
    op.drop_index(op.f('ix_macro_errors_slug'), table_name='macro_errors')
    op.drop_table('macro_errors')
    # ### end Alembic commands ###