"""remove nutritionnix

Revision ID: 80d74e135543
Revises: 36787d520729
Create Date: 2026-05-19 13:07:14.455681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80d74e135543'
down_revision: Union[str, None] = '36787d520729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_items', sa.Column('off_id', sa.String(length=64), nullable=True))
    op.add_column('nutrition_items', sa.Column('off_enriched', sa.Boolean(), nullable=False))
    op.alter_column('nutrition_items', 'slug',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('nutrition_items', 'nom_fr',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('nutrition_items', 'nom_en',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('nutrition_items', 'calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('nutrition_items', 'proteines',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('nutrition_items', 'glucides',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('nutrition_items', 'lipides',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('nutrition_items', 'ciqual_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='ciqual_id::integer')
    op.create_index(op.f('ix_nutrition_items_nom_fr'), 'nutrition_items', ['nom_fr'], unique=False)
    op.create_index(op.f('ix_nutrition_items_off_id'), 'nutrition_items', ['off_id'], unique=False)
    op.drop_column('nutrition_items', 'nutritionix_id')
    op.drop_column('nutrition_items', 'nutritionix_enriched')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_items', sa.Column('nutritionix_enriched', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('nutrition_items', sa.Column('nutritionix_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_nutrition_items_off_id'), table_name='nutrition_items')
    op.drop_index(op.f('ix_nutrition_items_nom_fr'), table_name='nutrition_items')
    op.alter_column('nutrition_items', 'ciqual_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('nutrition_items', 'lipides',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nutrition_items', 'glucides',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nutrition_items', 'proteines',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nutrition_items', 'calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('nutrition_items', 'nom_en',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('nutrition_items', 'nom_fr',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('nutrition_items', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_column('nutrition_items', 'off_enriched')
    op.drop_column('nutrition_items', 'off_id')
    # ### end Alembic commands ###