"""remove field

Revision ID: bb9d947887f2
Revises: c4fd80f5f501
Create Date: 2026-05-19 16:15:45.542378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb9d947887f2'
down_revision: Union[str, None] = 'c4fd80f5f501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_items', 'nutritionix_id')
    op.drop_column('nutrition_items', 'nutritionix_enriched')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_items', sa.Column('nutritionix_enriched', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('nutrition_items', sa.Column('nutritionix_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###