"""add_ciqual_archive_and_nutrition_fields

Revision ID: c4fd80f5f501
Revises: 80d74e135543
Create Date: 2026-05-19 15:04:18.565496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4fd80f5f501'
down_revision: Union[str, None] = '80d74e135543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciqual_archives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.add_column('nutrition_items', sa.Column('nom_sci', sa.String(length=512), nullable=True))
    op.add_column('nutrition_items', sa.Column('alim_grp_code', sa.String(length=20), nullable=True))
    op.add_column('nutrition_items', sa.Column('alim_ssgrp_code', sa.String(length=20), nullable=True))
    op.add_column('nutrition_items', sa.Column('alim_ssssgrp_code', sa.String(length=20), nullable=True))
    op.add_column('nutrition_items', sa.Column('code_confiance', sa.String(length=1), nullable=True))
    op.add_column('nutrition_items', sa.Column('nutritionix_id', sa.String(length=100), nullable=True))
    op.add_column('nutrition_items', sa.Column('nutritionix_enriched', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_nutrition_items_alim_grp_code'), 'nutrition_items', ['alim_grp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_items_alim_grp_code'), table_name='nutrition_items')
    op.drop_column('nutrition_items', 'nutritionix_enriched')
    op.drop_column('nutrition_items', 'nutritionix_id')
    op.drop_column('nutrition_items', 'code_confiance')
    op.drop_column('nutrition_items', 'alim_ssssgrp_code')
    op.drop_column('nutrition_items', 'alim_ssgrp_code')
    op.drop_column('nutrition_items', 'alim_grp_code')
    op.drop_column('nutrition_items', 'nom_sci')
    op.drop_table('ciqual_archives')
    # ### end Alembic commands ###