services:
# ══════════════════════════════════════════════════════════
# SGBD
# ══════════════════════════════════════════════════════════
  postgres-user:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - "5433:5432"                  # 5433 sur ta machine pour éviter les conflits
    volumes:
      - pgdata-user:/var/lib/postgresql/data   # données persistantes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_USER} -d ${POSTGRES_USER_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - nutriplanner

  postgres-recipe:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_RECIPE_DB}
      POSTGRES_USER: ${POSTGRES_RECIPE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_RECIPE_PASSWORD}
    ports:
      - "5434:5432"                  # 5433 sur ta machine pour éviter les conflits
    volumes:
      - pgdata-recipe:/var/lib/postgresql/data   # données persistantes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_RECIPE_USER} -d ${POSTGRES_RECIPE_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - nutriplanner

# ══════════════════════════════════════════════════════════
# SERVICE — user
# ══════════════════════════════════════════════════════════
  service-user:
    build:
      context: ./service-user
    container_name: nutriplanner-service-user
    ports:
      - "8001:8000"
    volumes:
      - ./service-user:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER_USER}:${POSTGRES_USER_PASSWORD}@postgres-user:5432/${POSTGRES_USER_DB}
    env_file:
      - .env
      - ./service-user/conf/.env
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - nutriplanner

# ══════════════════════════════════════════════════════════
# SERVICE — Recipe
# ══════════════════════════════════════════════════════════
  service-recipe:
    build:
      context: ./service-recipe
    container_name: nutriplanner-service-recipe
    ports:
      - "8002:8000"
    volumes:
      - ./service-recipe:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER_USER}:${POSTGRES_USER_PASSWORD}@postgres-user:5432/${POSTGRES_USER_DB}
    env_file:
      - .env
      - ./service-recipe/conf/.env
    depends_on:
      postgres-recipe:
        condition: service_healthy
    networks:
      - nutriplanner

networks:
  nutriplanner:
    driver: bridge
volumes:
  pgdata-user:
  pgdata-recipe: