"""init menu schema

Revision ID: e172bc1a8bb4
Revises: 
Create Date: 2026-05-15 20:36:26.851665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e172bc1a8bb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WEB', 'INSTAGRAM', 'YOUTUBE', name='crawltype', native_enum=False, length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('execution_hour', sa.Time(), nullable=False),
    sa.Column('last_crawl', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('WEB', 'INSTAGRAM', 'YOUTUBE', name='crawltype', native_enum=False, length=20), nullable=False),
    sa.Column('url_origin', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('WAITTING', 'VALID', 'REJECTED', name='crawlstatus', native_enum=False, length=20), nullable=False),
    sa.Column('validate_by', sa.UUID(), nullable=True),
    sa.Column('validate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['crawl_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_results')
    op.drop_table('crawl_sources')
    # ### end Alembic commands ###