sonar.projectKey=nutri-app-service-menu
sonar.organization=breizhooz
sonar.projectName=NutriApp - Menu Service
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
# On exclut les migrations Alembic de l'analyse de qualité
sonar.exclusions=alembic/**