"""init menu schema

Revision ID: 2816abe34c7b
Revises: 
Create Date: 2026-05-12 15:44:21.201707
"""
from alembic import op
import sqlalchemy as sa


revision = '2816abe34c7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_menus',
    sa.Column('slug', sa.String(length=350), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('nb_persons', sa.Integer(), nullable=False),
    sa.Column('caloric_target', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('exclusions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('free_tags', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_menus_slug'), 'weekly_menus', ['slug'], unique=True)
    op.create_table('menu_slots',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek', native_enum=False, length=50), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', name='mealtype', native_enum=False, length=50), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['weekly_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_slots_menu_id'), 'menu_slots', ['menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_slots_menu_id'), table_name='menu_slots')
    op.drop_table('menu_slots')
    op.drop_index(op.f('ix_weekly_menus_slug'), table_name='weekly_menus')
    op.drop_table('weekly_menus')
    # ### end Alembic commands ###