"""fix format data

Revision ID: 1fb75218d795
Revises: f4ab7a4a4cfd
Create Date: 2026-05-20 16:22:38.336035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "1fb75218d795"
down_revision: Union[str, None] = "f4ab7a4a4cfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lifestyle_profiles",
        sa.Column("profession_activity_level", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "nutrition_preferences",
        sa.Column(
            "budget_per_day_eur", sa.Numeric(precision=7, scale=2), nullable=True
        ),
    )
    op.add_column(
        "nutrition_preferences", sa.Column("excluded_foods", sa.JSON(), nullable=False)
    )
    op.drop_column("nutrition_preferences", "food_budget_monthly_eur")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nutrition_preferences",
        sa.Column(
            "food_budget_monthly_eur",
            sa.NUMERIC(precision=7, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("nutrition_preferences", "excluded_foods")
    op.drop_column("nutrition_preferences", "budget_per_day_eur")
    op.drop_column("lifestyle_profiles", "profession_activity_level")
    # ### end Alembic commands ###
