"""Initial models

Revision ID: f4ab7a4a4cfd
Revises:
Create Date: 2026-05-20 15:57:26.496349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f4ab7a4a4cfd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_composition_snapshots",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column(
            "body_fat_percentage", sa.Numeric(precision=4, scale=1), nullable=True
        ),
        sa.Column("lean_mass_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("bone_mass_kg", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("water_percentage", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_body_composition_snapshots_profile_id"),
        "body_composition_snapshots",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_body_composition_snapshots_slug"),
        "body_composition_snapshots",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "body_measurements_snapshots",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column("waist_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("hips_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("chest_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("shoulders_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("left_arm_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("right_arm_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("left_thigh_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("right_thigh_cm", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_body_measurements_snapshots_profile_id"),
        "body_measurements_snapshots",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_body_measurements_snapshots_slug"),
        "body_measurements_snapshots",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "excluded_foods",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("food_name", sa.String(length=200), nullable=False),
        sa.Column("food_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_excluded_foods_profile_id"),
        "excluded_foods",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_excluded_foods_slug"), "excluded_foods", ["slug"], unique=True
    )
    op.create_table(
        "food_allergies",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("allergen", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INTOLERANCE",
                "ALLERGY",
                name="allergyseverity",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_allergies_profile_id"),
        "food_allergies",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_food_allergies_slug"), "food_allergies", ["slug"], unique=True
    )
    op.create_table(
        "injuries",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("body_part", sa.String(length=100), nullable=False),
        sa.Column("injury_type", sa.String(length=200), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_chronic", sa.Boolean(), nullable=False),
        sa.Column("diagnosed_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_injuries_profile_id"), "injuries", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_injuries_slug"), "injuries", ["slug"], unique=True)
    op.create_table(
        "lifestyle_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("stress_level", sa.String(length=32), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("chronotype", sa.String(length=32), nullable=True),
        sa.Column("alcohol_frequency", sa.String(length=32), nullable=True),
        sa.Column("is_smoker", sa.Boolean(), nullable=False),
        sa.Column("sedentary_hours_per_day", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lifestyle_profiles_profile_id"),
        "lifestyle_profiles",
        ["profile_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_lifestyle_profiles_slug"), "lifestyle_profiles", ["slug"], unique=True
    )
    op.create_table(
        "medical_conditions",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "METABOLIC",
                "DIGESTIVE",
                "CARDIOVASCULAR",
                "HORMONAL",
                "OTHER",
                name="medicalcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("condition_name", sa.String(length=200), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medical_conditions_profile_id"),
        "medical_conditions",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medical_conditions_slug"), "medical_conditions", ["slug"], unique=True
    )
    op.create_table(
        "medications",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("medication_name", sa.String(length=200), nullable=False),
        sa.Column("impacts_metabolism", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medications_profile_id"), "medications", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_medications_slug"), "medications", ["slug"], unique=True)
    op.create_table(
        "nutrition_preferences",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "diet_type",
            sa.Enum(
                "OMNIVORE",
                "VEGETARIAN",
                "VEGAN",
                "PESCATARIAN",
                "KETO",
                "HALAL",
                "KOSHER",
                "NO_PORK",
                "OTHER",
                name="diettype",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("diet_type_other", sa.String(length=100), nullable=True),
        sa.Column(
            "main_goal",
            sa.Enum(
                "WEIGHT_LOSS",
                "MUSCLE_GAIN",
                "BODY_RECOMPOSITION",
                "SPORTS_PERFORMANCE",
                "MAINTENANCE",
                name="maingoal",
                native_enum=False,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("meals_per_day", sa.SmallInteger(), nullable=True),
        sa.Column("snacks_per_day", sa.SmallInteger(), nullable=True),
        sa.Column("practices_if", sa.Boolean(), nullable=False),
        sa.Column("fasting_window_hours", sa.SmallInteger(), nullable=True),
        sa.Column(
            "cooking_level",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="cookinglevel",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column(
            "cooking_time_available",
            sa.Enum(
                "QUICK",
                "MODERATE",
                "EXTENDED",
                name="cookingtime",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column(
            "cooking_for",
            sa.Enum(
                "SOLO",
                "COUPLE",
                "FAMILY",
                "MEAL_PREP",
                name="cookingfor",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column("hydration_target_ml", sa.Integer(), nullable=True),
        sa.Column("supplements", sa.JSON(), nullable=False),
        sa.Column(
            "food_budget_monthly_eur", sa.Numeric(precision=7, scale=2), nullable=True
        ),
        sa.Column("medical_contraindications", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrition_preferences_profile_id"),
        "nutrition_preferences",
        ["profile_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_nutrition_preferences_slug"),
        "nutrition_preferences",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "performance_metrics",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column("vo2max", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("vma_kmh", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("ftp_watts", sa.SmallInteger(), nullable=True),
        sa.Column("one_rm_squat_kg", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column(
            "one_rm_bench_press_kg", sa.Numeric(precision=5, scale=1), nullable=True
        ),
        sa.Column(
            "one_rm_deadlift_kg", sa.Numeric(precision=5, scale=1), nullable=True
        ),
        sa.Column(
            "one_rm_overhead_press_kg", sa.Numeric(precision=5, scale=1), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_performance_metrics_profile_id"),
        "performance_metrics",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_metrics_slug"),
        "performance_metrics",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "biological_sex",
            sa.Enum(
                "MALE",
                "FEMALE",
                "NOT_SPECIFIED",
                name="biologicalsex",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("target_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_slug"), "profiles", ["slug"], unique=True)
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "sports_profiles",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("sports", sa.JSON(), nullable=False),
        sa.Column(
            "practice_level",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                "COMPETITIVE",
                name="practicelevel",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("sessions_per_week", sa.SmallInteger(), nullable=False),
        sa.Column("avg_session_duration_min", sa.SmallInteger(), nullable=False),
        sa.Column("avg_intensity_rpe", sa.SmallInteger(), nullable=False),
        sa.Column("resting_heart_rate_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sports_profiles_profile_id"),
        "sports_profiles",
        ["profile_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sports_profiles_slug"), "sports_profiles", ["slug"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sports_profiles_slug"), table_name="sports_profiles")
    op.drop_index(op.f("ix_sports_profiles_profile_id"), table_name="sports_profiles")
    op.drop_table("sports_profiles")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_slug"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_performance_metrics_slug"), table_name="performance_metrics")
    op.drop_index(
        op.f("ix_performance_metrics_profile_id"), table_name="performance_metrics"
    )
    op.drop_table("performance_metrics")
    op.drop_index(
        op.f("ix_nutrition_preferences_slug"), table_name="nutrition_preferences"
    )
    op.drop_index(
        op.f("ix_nutrition_preferences_profile_id"), table_name="nutrition_preferences"
    )
    op.drop_table("nutrition_preferences")
    op.drop_index(op.f("ix_medications_slug"), table_name="medications")
    op.drop_index(op.f("ix_medications_profile_id"), table_name="medications")
    op.drop_table("medications")
    op.drop_index(op.f("ix_medical_conditions_slug"), table_name="medical_conditions")
    op.drop_index(
        op.f("ix_medical_conditions_profile_id"), table_name="medical_conditions"
    )
    op.drop_table("medical_conditions")
    op.drop_index(op.f("ix_lifestyle_profiles_slug"), table_name="lifestyle_profiles")
    op.drop_index(
        op.f("ix_lifestyle_profiles_profile_id"), table_name="lifestyle_profiles"
    )
    op.drop_table("lifestyle_profiles")
    op.drop_index(op.f("ix_injuries_slug"), table_name="injuries")
    op.drop_index(op.f("ix_injuries_profile_id"), table_name="injuries")
    op.drop_table("injuries")
    op.drop_index(op.f("ix_food_allergies_slug"), table_name="food_allergies")
    op.drop_index(op.f("ix_food_allergies_profile_id"), table_name="food_allergies")
    op.drop_table("food_allergies")
    op.drop_index(op.f("ix_excluded_foods_slug"), table_name="excluded_foods")
    op.drop_index(op.f("ix_excluded_foods_profile_id"), table_name="excluded_foods")
    op.drop_table("excluded_foods")
    op.drop_index(
        op.f("ix_body_measurements_snapshots_slug"),
        table_name="body_measurements_snapshots",
    )
    op.drop_index(
        op.f("ix_body_measurements_snapshots_profile_id"),
        table_name="body_measurements_snapshots",
    )
    op.drop_table("body_measurements_snapshots")
    op.drop_index(
        op.f("ix_body_composition_snapshots_slug"),
        table_name="body_composition_snapshots",
    )
    op.drop_index(
        op.f("ix_body_composition_snapshots_profile_id"),
        table_name="body_composition_snapshots",
    )
    op.drop_table("body_composition_snapshots")
    # ### end Alembic commands ###
