from enum import Enum as PyEnum

class DifficultyLevel(str, PyEnum):
    """Level of difficulty"""
    EASY = "enums.difficulty.easy"
    MEDIUM = "enums.difficulty.medium"
    HARD = "enums.difficulty.hard"

class RecipeOrigin(str, PyEnum):
    """Origin of recipe"""
    WEB = "enums.origin_recipe.web"
    BOOK = "enums.origin_recipe.book"
    TV = "enums.origin_recipe.tv"
    PERSONAL = "enums.origin_recipe.personal"

class CourseType(str, PyEnum):
    """Type of moment recipe"""
    STARTER = "enums.course_type.starter"
    MAIN_COURSE = "enums.course_type.main"
    DESSERT = "enums.course_type.dessert"

class CuisineOrigin(str, PyEnum):
    """Origin of cuisine"""
    EUROPE = "enums.origin_recipe.cuisine_origine.europe"
    FRENCH = "enums.origin_recipe.cuisine_origine.french"
    ITALIAN = "enums.origin_recipe.cuisine_origine.italian"
    SPANISH = "enums.origin_recipe.cuisine_origine.spanish"
    GREEK = "enums.origin_recipe.cuisine_origine.greek"
    GERMAN = "enums.origin_recipe.cuisine_origine.german"
    ASIA = "enums.origin_recipe.cuisine_origine.asia"
    CHINESE = "enums.origin_recipe.cuisine_origine.chinese"
    JAPANESE = "enums.origin_recipe.cuisine_origine.japanese"
    THAI = "enums.origin_recipe.cuisine_origine.thai"
    INDIAN = "enums.origin_recipe.cuisine_origine.indian"
    KOREAN = "enums.origin_recipe.cuisine_origine.korean"
    VIETNAMESE = "enums.origin_recipe.cuisine_origine.vietnamese"
    AFRICA = "enums.origin_recipe.cuisine_origine.africa"
    MOROCCAN = "enums.origin_recipe.cuisine_origine.moroccan"
    ETHIOPIAN = "enums.origin_recipe.cuisine_origine.ethiopian"
    SENEGALESE = "enums.origin_recipe.cuisine_origine.senegalese"
    SOUTH_AMERICA = "enums.origin_recipe.cuisine_origine.south_america"
    MEXICAN = "enums.origin_recipe.cuisine_origine.mexican"
    AMERICAN = "enums.origin_recipe.cuisine_origine.american"
    BRAZILIAN = "enums.origin_recipe.cuisine_origine.brazilian"
    PERUVIAN = "enums.origin_recipe.cuisine_origine.peruvian"
    MIDDLE_EAST = "enums.origin_recipe.cuisine_origine.middle_east"
    LEBANESE = "enums.origin_recipe.cuisine_origine.lebanese"
    TURKISH = "enums.origin_recipe.cuisine_origine.turkish"
    IRANIAN = "enums.origin_recipe.cuisine_origine.iranian"
    OCEANIA = "enums.origin_recipe.cuisine_origine.oceania"
    AUSTRALIAN = "enums.origin_recipe.cuisine_origine.australian"
    POLYNESIAN = "enums.origin_recipe.cuisine_origine.polynesian"
