server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxies les specs côté serveur — zéro CORS côté browser
    location /specs/service-user.json {
        proxy_pass http://service-user:8000/openapi.json;
        proxy_set_header Host api-users.localhost;
    }
    location /specs/service-recipe.json {
        proxy_pass http://service-recipe:8000/openapi.json;
        proxy_set_header Host api-recipe.localhost;
    }
    location /specs/service-menu.json {
        proxy_pass http://service-menu:8000/openapi.json;
        proxy_set_header Host api-menu.localhost;
    }
    location /specs/service-crawler.json {
        proxy_pass http://service-crawler:8000/openapi.json;
        proxy_set_header Host api-crawler.localhost;
    }
    location /specs/service-nutrition.json {
        proxy_pass http://service-nutrition:8000/openapi.json;
        proxy_set_header Host api-nutrition.localhost;
    }
    location /specs/service-notification.json {
        proxy_pass http://service-notification:8000/openapi.json;
        proxy_set_header Host api-notification.localhost;
    }
    location /specs/service-profile.json {
        proxy_pass http://service-profile:8000/openapi.json;
        proxy_set_header Host api-profile.localhost;
    }
}